# Generated by Django 5.2.7 on 2025-10-14 16:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('area', models.CharField(choices=[('Tecnologia', 'Tecnología'), ('Administracion', 'Administración'), ('Construccion', 'Construcción'), ('Salud', 'Salud'), ('Gastronomia', 'Gastronomía')], max_length=20)),
                ('nivel', models.CharField(max_length=15)),
                ('duracion_semestres', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('Sesiones', 'Sesiones'), ('Calidad', 'Calidad'), ('Tiempo', 'Tiempo'), ('Especialidad', 'Especialidad'), ('Comunidad', 'Comunidad')], max_length=15)),
                ('puntos', models.PositiveIntegerField(default=10)),
                ('icono', models.CharField(default='🏆', max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ciudad', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro'), ('Prefiero_no_decir', 'Prefiero no decir')], default='Prefiero_no_decir', max_length=20)),
                ('sede', models.CharField(blank=True, max_length=100)),
                ('carrera', models.CharField(blank=True, max_length=100)),
                ('semestre_actual', models.PositiveIntegerField(default=1)),
                ('promedio_general', models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=3)),
                ('beneficio_gratuidad', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Egresado', 'Egresado'), ('Retirado', 'Retirado'), ('Suspendido', 'Suspendido')], default='Activo', max_length=15)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('es_tutor', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('semestre', models.PositiveIntegerField()),
                ('es_critica', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='main.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Sesion_Agendada', 'Sesión Agendada'), ('Recordatorio', 'Recordatorio'), ('Cancelacion', 'Cancelación'), ('Evaluacion', 'Evaluación'), ('Logro', 'Logro'), ('Sistema', 'Sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_certificacion', models.DateField()),
                ('nivel', models.CharField(choices=[('Novato', 'Novato'), ('Bronce', 'Bronce'), ('Plata', 'Plata'), ('Oro', 'Oro'), ('Platino', 'Platino'), ('Elite', 'Elite')], default='Novato', max_length=10)),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=3)),
                ('total_sesiones', models.PositiveIntegerField(default=0)),
                ('horas_acumuladas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('especialidades', models.TextField(blank=True)),
                ('modalidad_preferida', models.CharField(choices=[('Presencial', 'Presencial'), ('Online', 'Online'), ('Ambas', 'Ambas')], default='Ambas', max_length=15)),
                ('bio_descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SesionTutoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Online', 'Online')], max_length=15)),
                ('fecha_programada', models.DateTimeField()),
                ('duracion_minutos', models.PositiveIntegerField(default=60)),
                ('estado', models.CharField(choices=[('Programada', 'Programada'), ('En_Curso', 'En Curso'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada'), ('No_Show', 'No Show')], default='Programada', max_length=15)),
                ('tema_solicitud', models.TextField()),
                ('notas_tutor', models.TextField(blank=True)),
                ('calificacion_tutor', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('calificacion_tutorado', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='main.asignatura')),
                ('tutorado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_como_estudiante', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_como_tutor', to='main.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('Guia', 'Guía'), ('Ejercicios', 'Ejercicios'), ('Video', 'Video'), ('Presentacion', 'Presentación'), ('Documento', 'Documento'), ('Otro', 'Otro')], max_length=15)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='recursos/')),
                ('contenido', models.TextField(blank=True)),
                ('descargas', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='main.asignatura')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='main.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioLogro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtencion', models.DateTimeField(auto_now_add=True)),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='main.logro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'logro')},
            },
        ),
    ]
