# Generated by Django 5.2.7 on 2025-10-14 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_disponibilidadtutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidadtutor',
            name='dia_semana',
        ),
        migrations.AddField(
            model_name='disponibilidadtutor',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], default='Lunes', max_length=12),
        ),
        migrations.AlterField(
            model_name='disponibilidadtutor',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tutor'),
        ),
    ]
