# Generated by Django 5.2.7 on 2025-10-14 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_disponibilidadtutor_dia_semana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesiontutoria',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Denegada', 'Denegada'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada'), ('No_Show', 'No Show')], default='Pendiente', max_length=15),
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='main.sesiontutoria')),
            ],
        ),
    ]
