# Generated by Django 5.2.7 on 2025-10-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_sesiontutoria_estado_mensaje'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['fecha_envio']},
        ),
        migrations.AlterModelOptions(
            name='sesiontutoria',
            options={'ordering': ['-fecha_programada']},
        ),
        migrations.AddField(
            model_name='sesiontutoria',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sesiontutoria',
            name='razon_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('Sesion_Agendada', 'Sesión Agendada'), ('Sesion_Aceptada', 'Sesión Aceptada'), ('Sesion_Rechazada', 'Sesión Rechazada'), ('Recordatorio', 'Recordatorio'), ('Cancelacion', 'Cancelación'), ('Evaluacion', 'Evaluación'), ('Logro', 'Logro'), ('Sistema', 'Sistema')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidadtutor',
            unique_together={('tutor', 'dia', 'hora_inicio')},
        ),
    ]
