# Generated by Django 5.2.7 on 2025-10-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_mensaje_options_alter_sesiontutoria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='años_experiencia',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
