# Generated by Django 5.2.7 on 2025-10-15 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tutor_años_experiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sesiontutoria'),
        ),
    ]
