# Generated by Django 5.2.7 on 2025-10-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_notificacion_sesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='nivel',
            field=models.CharField(choices=[('Novato', 'Novato'), ('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado'), ('Erudito', 'Erudito'), ('Iluminado', 'Iluminado')], default='Novato', max_length=20),
        ),
    ]
